Conguence
filp8/gauss_elimination pull request #27
Opened 2024-01-09 08:47 UTC by filp8

ho fatto una strozzata mi dovevo spostare sul main mannaggia a me, comunque ho fatto una cosa al volo sulle congruenze

2024-01-09 14:51 UTC, LucaSforza requested changes
Va fatto solo un cambiamento

2024-01-09 14:51 UTC, LucaSforza commented on gauss.py
> +                nline.append(Fraction.from_float(num))
troppe condizioni non necessarie
```python
type(num) == int
```
e 
```python
type(num) == str
```

possono essere sostitutito da un or tra le due condizioni

2024-01-09 15:07 UTC, LucaSforza approved these changes

2024-01-09 15:10 UTC, LucaSforza requested changes

2024-01-09 15:10 UTC, LucaSforza commented on congruence.py
> +printMat(multiplyTableCongruence(ins1,7))
Da togliere queste 
```python 
printMat(...)
```
 e mettere tutti questi test in un file di test apposito

2024-01-10 00:12 UTC, filp8 reviewed
I test li ho aggiunti  un poi di commit più in la

2024-01-11 12:28 UTC, LucaSforza commented on congruence.py
> +printMat(multiplyTableCongruence(generatoreR(1,9),9,moltiplicazione))
da togliere questo print e semmai aggiungere test su queste cose

2024-01-11 12:31 UTC, LucaSforza requested changes
Semplicemente da aggiungere i test e poi può essere mergiato (se vuoi li metto io se non ti va)

2024-01-11 12:31 UTC, LucaSforza commented on congruence.py
> +printMat(multiplyTableCongruence(generatoreR(1,9),9,moltiplicazione))
da eliminare questo printMat e aggiungere dei test per queste cose

2024-01-11 12:31 UTC, LucaSforza commented on tests.py
> -from copy import deepcopy
bisogna rimettere questo file ed un altro con i nuovi test

2024-01-11 13:38 UTC, LucaSforza requested changes
Da togliere i `printMat` e metterli in dei test, ma il bug #29 è stato risolto

2024-01-11 21:07 UTC, LucaSforza commented
Attenzione che ci sono dei conflitti con il main, con VSCode però dovrebbero essere semplici da risolvere

2024-01-27 23:26 UTC, LucaSforza requested changes
Non credo che hai caricato i file con i test, poi bisogna sistemare i conflitti con il main

2024-01-27 23:35 UTC, filp8 commented
secondo te ci stanno altre cose da fare??

2024-01-28 00:06 UTC, LucaSforza commented
> secondo te ci stanno altre cose da fare??

Calcola manca il test per i file che era stato eliminato ed ora non ci sta più, però ho visto che hai aggiunto i test per congruence. Quindi manca solo quelli normali (che li puoi riprendere quel file dal main)

Poi bisogna risolvere i conflitti con il main che senza risolvere quelli neanche volendo si più mergiare

2024-01-28 11:19 UTC, merged

2024-01-28 11:19 UTC, LucaSforza approved these changes
Ho visto che hai aggiunto i test e ora ci sta tutto, cambio giusto il nome del file tests.py per far capire che riguarda gli algoritmi di gauss e poi faccio il merge